### ISSUE TITLE
Docs say "the npm package includes node-webcrypto-ossl;"

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [PeculiarVentures/xadesjs#30]
After npm install xadesjs, I don't see node-webcrypto-ossl in it's node_modules,  is the Readme incorrect and I need to install it separately to use with node?

**Comment by rmhrisk** [comment]
It is:

**Comment by WhatFreshHellIsThis** [comment]
Did you just change something because I just installed about 5 hours ago here is the dependencies snipped from it's package.json:
```

},
  "homepage": "https://github.com/PeculiarVentures/xadesjs#readme",
  "dependencies": {
    "co": "^4.6.0",
    "node.extend": "^1.1.5",
    "xmldom": "^0.1.22",
    "xpath.js": "^1.0.6",
    "pkijs": "^1.3.17",
    "asn1js": "^1.2.12"
  },
  "devDependencies": {
    "express": "^4.13.4"
  },
  "gitHead": "e08171ce351f35fd69eb89ceb76bfee5c624121e",
  "_id": "xadesjs@1.0.0",

```

**Comment by WhatFreshHellIsThis** [comment]
There is undoubtedly an issue with this package.  I uninstalled everything then ran npm install xadesjs 5 minutes ago and here is what happened:


```
john@debian-john:~/Documents/rockfish/lib$ npm install xadesjs --save
npm WARN package.json rockfish@1.0.0 No repository field.
npm WARN package.json rockfish@1.0.0 No README data
npm WARN package.json rockfish@1.0.0 license should be a valid SPDX license expression
xadesjs@1.0.0 ../node_modules/xadesjs
├── co@4.6.0
├── xpath.js@1.0.6
├── xmldom@0.1.22
├── asn1js@1.2.12
├── node.extend@1.1.5 (is@3.1.0)
└── pkijs@1.3.27
john@debian-john:~/Documents/rockfish/lib$ 

```

As you can see it did not install node-webcrypto-ossl

**Comment by rmhrisk** [comment]
I did not "just change something", I did not do the install based on npm though, the repository has included node-webcrypto-ossl for quite some time, you are welcome to look at the checkin history to confirm things.

I will find time to publish a updated npm module in the next week or so.

**Comment by WhatFreshHellIsThis** [comment]
ok so issue is npm package is broken, maybe mention that in readme if you're not going to fix it for a while?

Maybe i'm atypical but I personally don't clone repos of tools , I just run npm install and work with examples.

**Comment by rmhrisk** [comment]
Well, I don't know I would say it is broken. That said in 1.0 we did not include the webcrypto-openssl package as it is optional (don't need it in the browser and on node you may prefer the node-webcryto-p11 module, or another pollyfill).

We have since decided that it would be easier for those who want to use the project on node if we included the node-webcryto-ossl dependency explicitly even if not all users need it. We have simply not released a new version yet as we have been working on updates to the library and I wanted to wait until we had a new major version.

You did find issues the README and I thank you for pointing those out, I have ran through them all again and they worked for me (famous last words) but if you find any other issues please do not hesitate to let us know.


Ryan

**Comment by rmhrisk** [comment]
Closing as I believe all issues have been resolved, reopen if you feel otherwise.

**Comment by WhatFreshHellIsThis** [comment]
I guess my way of thinking is if you can't just install it and run example code then that is an issue that causes friction for a new user who really just wants to try it out and see if it's a suitable tool or not.  But I totally get your point of view, you expect users to clone the repo and then try the examples, I prefer to try examples in my own project so I know it will work for me, Potato potato I guess.
Cheers!

**Comment by rmhrisk** [comment]
Your welcome?
