### ISSUE TITLE
PFX File

### ISSUE THREAD

**Issue by danieljoppi** [PeculiarVentures/xadesjs#40]
Can I use PFX cert?
Have one example?

**Comment by rmhrisk** [comment]
In this library, we focused on only XADES/XMLDSIG, we utilized WebCrypto for all cryptographic operations.

If you would like to open a PKCS#12 you can do so with a library we produce called PKIjs, here is a sample  - https://pkijs.org/examples/PKCS12SimpleExample.html

Here are some notes about that project and its limitations, as well as the security issues with PKCS#12 - https://unmitigatedrisk.com/?p=543

In general, I would recommend that you look at using SoftHSM to store the keys instead of a PKCS12 anyway. PKCS12 uses weak crypto and at least SoftHSM uses modern algorithms.

I have not done this personally (we use HSMs and smart cards) but you should be able to do this with pkcs11-tool and SoftHSM2 just fine.

We do not have an example that uses PKCS#12 and XADES as they are two separate libraries and have been focusing on features and test coverage over building sample applications. A pull request with a sample would be appreciated.

**Comment by danieljoppi** [comment]
no problem ... thanks !!

I will test
