### ISSUE TITLE
Error installing: remote invalid username or password when cloning repo

### ISSUE THREAD

**Issue by omaralqady** [PeculiarVentures/xadesjs#48]
```
npm ERR! git clone --template=/home/dir/.npm/_git-remotes/_templates --mirror https://github.com/PeculiarVentures/asn1js-es6.git /home/dir/.npm/_git-remotes/git-https-github-com-PeculiarVentures-asn1js-es6-git-f4b3f41f: Cloning into bare repository '/home/dir/.npm/_git-remotes/git-https-github-com-PeculiarVentures-asn1js-es6-git-f4b3f41f'...

npm ERR! git clone --template=/home/dir/.npm/_git-remotes/_templates --mirror https://github.com/PeculiarVentures/asn1js-es6.git /home/dir/.npm/_git-remotes/git-https-github-com-PeculiarVentures-asn1js-es6-git-f4b3f41f: remote: Invalid username or password.

npm ERR! git clone --template=/home/dir/.npm/_git-remotes/_templates --mirror https://github.com/PeculiarVentures/asn1js-es6.git /home/dir/.npm/_git-remotes/git-https-github-com-PeculiarVentures-asn1js-es6-git-f4b3f41f: fatal: Authentication failed for 'https://github.com/PeculiarVentures/asn1js-es6.git/'
```

I get the above error when trying to install from `npm` (simply running `npm install xadesjs`), is there something I should change? Or is there a problem with the repo?

**Comment by microshine** [comment]
@omaralqady Thank you for your issue. I made some updates. Could you try to install `xadesjs` again?

if you want to run nodejs test you have to install [node-webcrypto-ossl](https://www.npmjs.com/package/node-webcrypto-ossl) first.

```
npm install node-webcrypto-ossl
```

I don't use this module as required for `xadesjs`, because there are some nodejs webcrypto implementations.

if you use `xadesjs` from browser you don't have to install webcrypto. Module uses default WebCrypto API from browser. I recomend to use [webcrypto-liner](https://www.npmjs.com/package/webcrypto-liner)

[HTML example](https://github.com/PeculiarVentures/xadesjs/blob/master/examples/html/sign.html#L14-L18)

**Comment by omaralqady** [comment]
@microshine Thank you for your prompt response and handling.

The installation works now, and I'm using it with node and I saw in the docs that I have to install `node-webcrypto-ossl` so I did that as well.

Thank you :)
