### ISSUE TITLE
pkcs11 algorithm compatibility, sha-1 hash does not work

### ISSUE THREAD

**Issue by Ulterior** [PeculiarVentures/xadesjs#92]
I was trying to understand why my pkcs11 token couldnt sign/verify with sha-1 until I saw this:

```
                        case graphene_pk11_1.KeyType.RSA: {
                            if (p11Key.sign || p11Key.verify) {
                                alg.name = "RSASSA-PKCS1-v1_5";
                            }
                            else {
                                alg.name = "RSA-OAEP";
                            }
                            alg.hash = { name: "SHA-256" };
                            break;
                        }
```
changing the value on key after it has been retrieved gives other code processing errors, so the question is -  is only SHA-256 supported?

**Comment by rmhrisk** [comment]
Our libraries are generally based on WebCrypto which does not support SHA1.

This is because it’s been considered very weak for about a decade, practically broken for the last 4 (https://shattered.io/) and it is getting weaker every day (https://www.google.com/amp/s/www.zdnet.com/google-amp/article/sha-1-collision-attacks-are-now-actually-practical-and-a-looming-danger/).

We do add support for weak and broken algorithms to things as seen in libraries like webcrypto-liner and pv/webcrypto but do practically go forward with the goal of doing so because we do not want to encourage the use of webcrypto.

We would consider a conservative PR that enabled verification in the name of interop with legacy files but would strongly recommend that all new signings happen with SHA-256.

**Comment by microshine** [comment]
@Ulterior What library do you use? If you are using WebCrypto with `keyStorage` it allows getting keys with a custom algorithm

https://github.com/PeculiarVentures/node-webcrypto-p11/blob/master/src/key_storage.ts#L48-L50
```ts
public async getItem(key: string): Promise<CryptoKey>;
public async getItem(key: string, algorithm: Algorithm, usages: KeyUsage[]): Promise<CryptoKey>;
```

**Comment by Ulterior** [comment]
@microshine thank you, it works if specifying explicitly to getItem

**Comment by rmhrisk** [comment]
Is all you need fetching a item?

**Comment by Ulterior** [comment]
@rmhrisk I am cycling through keys in my PKCS11 token and wasnt specifying algorithm for getItem, therefore verification and signing was using default 'wrong' hash.

**Comment by microshine** [comment]
```js
const indexes = await crypto.keyStorage.keys();
for (const index of indexes) {
  const key = await crypto.keyStorage.getItem(); // get with default alg
  if (key && (key.algorithm.name === "RSASSA-PKCS1-v1_5" || key.algorithm.name === "RSA-PSS")) {
    // ket the same key with anouther algorithm
    const rsaKey = await crypto.keyStorage.getItem(index, {name: "RSASSA-PKCS1-v1_5", hash: "SHA-1"}, ["sign"]);
    const signature = await crypto.subtle.sign("RSASSA-PKCS1-v1_5", rsaKey, data); 
  }
}
```
